export const products = [
  {
    _id: 'p1',
    name: 'Fresh Organic Tomatoes',
    category: 'Vegetables',
    price: 40,
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1546470427-e26264fde208?auto=format&fit=crop&q=80&w=500',
    images: [],
    videos: [],
    description: 'Fresh, locally grown organic tomatoes. Perfect for salads and cooking.',
    isOrganic: true,
    farmerId: 'f1',
  },
  {
    _id: 'p2',
    name: 'Green Spinach Bundle',
    category: 'Leafy Greens',
    price: 30,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=500',
    images: [],
    videos: [],
    description: 'Nutrient-rich spinach leaves, freshly harvested from organic farms.',
    isOrganic: true,
    farmerId: 'f2',
  },
  {
    _id: 'p3',
    name: 'Farm Fresh Carrots',
    category: 'Vegetables',
    price: 50,
    stock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=500',
    images: [],
    videos: [],
    description: 'Sweet and crunchy carrots, perfect for salads and cooking.',
    isOrganic: true,
    farmerId: 'f3',
  },
  {
    _id: 'p4',
    name: 'Organic Cucumber',
    category: 'Vegetables',
    price: 35,
    stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1604977042946-1eecc30f269e?auto=format&fit=crop&q=80&w=500',
    images: [],
    videos: [],
    description: 'Cool and crisp cucumbers, great for salads and raitas.',
    isOrganic: true,
    farmerId: 'f1',
  },
  {
    _id: 'p5',
    name: 'Fresh Strawberries',
    category: 'Fruits',
    price: 120,
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&q=80&w=500',
    images: [],
    videos: [],
    description: 'Sweet and juicy strawberries, perfect for desserts or snacking.',
    isOrganic: true,
    farmerId: 'f2',
  },
  {
    _id: 'p6',
    name: 'Organic Brown Rice',
    category: 'Grains',
    price: 85,
    stock: 100,
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=500',
    images: [],
    videos: [],
    description: 'Nutritious brown rice, locally grown and naturally processed.',
    isOrganic: true,
    farmerId: 'f3',
  },
  {
    _id: 'p7',
    name: 'Fresh Cow Milk',
    category: 'Dairy',
    price: 60,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=500',
    images: [],
    videos: [],
    description: 'Fresh cow milk from grass-fed cows, delivered daily.',
    isOrganic: true,
    farmerId: 'f4',
  },
  {
    _id: 'p8',
    name: 'Organic Eggs',
    category: 'Dairy',
    price: 90,
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1509479100390-f83a8349e79c?auto=format&fit=crop&q=80&w=500',
    images: [],
    videos: [],
    description: 'Free-range organic eggs from healthy hens.',
    isOrganic: true,
    farmerId: 'f4',
  }
];

export const categories = [
  {
    id: 1,
    name: "Vegetables",
    icon: "🥕",
  },
  {
    id: 2,
    name: "Fruits",
    icon: "🍎",
  },
  {
    id: 3,
    name: "Leafy Greens",
    icon: "🥬",
  },
  {
    id: 4,
    name: "Herbs",
    icon: "🌿",
  }
];

export const farmers = [
  {
    _id: 'f1',
    name: 'Ramesh Kumar',
    email: 'ramesh@example.com',
    phone: '9876543210',
    address: 'Bangalore Rural',
    farmName: 'Ramesh Organic Farm',
    farmDescription: 'Third-generation farmer specializing in organic vegetables.',
    farmImages: ['https://images.unsplash.com/photo-1628044565269-699506c9fff1?auto=format&fit=crop&q=80&w=800'],
    farmVideos: [],
    latitude: 12.9721,
    longitude: 77.5933,
    role: 'farmer',
  },
  {
    _id: 'f2',
    name: 'Lakshmi Devi',
    email: 'lakshmi@example.com',
    phone: '9876501234',
    address: 'Mysore',
    farmName: 'Lakshmi Farms',
    farmDescription: 'Passionate about sustainable farming and organic produce.',
    farmImages: ['https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&q=80&w=800'],
    farmVideos: [],
    latitude: 12.2958,
    longitude: 76.6394,
    role: 'farmer',
  },
  {
    _id: 'f3',
    name: 'Manjunath',
    email: 'manjunath@example.com',
    phone: '9845012345',
    address: 'Tumkur',
    farmName: 'Manjunath Agro',
    farmDescription: 'Growing healthy grains and vegetables with care.',
    farmImages: ['https://images.unsplash.com/photo-1605810230434-7631ac76ec61?auto=format&fit=crop&q=80&w=800'],
    farmVideos: [],
    latitude: 13.3409,
    longitude: 77.1010,
    role: 'farmer',
  },
  {
    _id: 'f4',
    name: 'Venkatesh',
    email: 'venkatesh@example.com',
    phone: '9811122233',
    address: 'Mandya',
    farmName: 'Mandya Dairy',
    farmDescription: 'Fresh dairy products from grass-fed cattle.',
    farmImages: ['https://images.unsplash.com/photo-1576765608550-cb8d439b8592?auto=format&fit=crop&q=80&w=800'],
    farmVideos: [],
    latitude: 12.5223,
    longitude: 76.9000,
    role: 'farmer',
  },
];
